export const homeObjOne = {
    id: 'about', 
    lightBg: false,
    lightText: true,
    lighTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transactions with zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without geeting charged any fees',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/undraw_off_road_9oae.png'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
};